### ISSUE TITLE
Streaming fails without restart

### ISSUE THREAD

**Issue by david-molnar-oculai** [AxisCommunications/axis-aws-kinesis-vsp#32]
We run the docker image provided from this repo on an AXIS P1467-LE Bullet Camera. The streaming works as expected. But after few hours of streaming the following error occurs:

```
Caught SIGSEGV
exec gdb failed: No such file or directory
Spinning.  Please run 'gdb gst-launch-1.0 8' to continue debugging, Ctrl-C to quit, or Ctrl-\ to dump core.
```

The process is not restarted and the streaming stops.

It would be nice, that the process just exits and it is restarted by Docker automatically.

**Comment by bsriramprasad** [comment]
Thanks for the issue and the associated PR, we accepted your contribution with heartfelt thank you! apologies again for delay in addressing the feedback.
